# Generated by Django 4.1 on 2023-03-10 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='database',
            name='c_name',
        ),
    ]
