# Generated by Django 4.1 on 2023-03-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_database_c_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='c_count',
            field=models.TextField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=2),
        ),
    ]
